apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aymoag1er-java-quarkus
  janus-idp.io/tekton: aymoag1er-java-quarkus
  backstage.io/kubernetes-id: aymoag1er-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aymoag1er-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
